# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d290adb66db0752adfb2feadf842b1b7c971e2677117b4d170f3fb53566a7b5c60ebe82c5c7d151d158fa36da6281be2955c458ff4626fc2ad423a6f1cf5c64e

test:
  secret_key_base: 93a136b823eb52114547b6485cc86ebac6a0c81577d0d69e3b5cc43dd4cfea1f71c2dd71e5d92f8679b559bba7727d9c6e81d7fc15a89fb6af7459e2ec3079f4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
